use futures::executor::block_on;
use qsk_errors as errors;

use evdev;
use evdev::uinput;

use qsk_events as event;
use qsk_errors::Result;

pub struct Device {
    input: evdev::EventStream,
    output: evdev::uinput::VirtualDevice,
}

impl Device {
    pub fn from_evdev_device(mut d: evdev::Device) -> errors::Result<Device> {
        d.grab()?;
        let mut vdb = uinput::VirtualDeviceBuilder::new()?;
        vdb = vdb.name("meow");
        if let Some(supported_keys) = d.supported_keys() {
            vdb = vdb.with_keys(supported_keys)?;
        } else {
            return Err(errors::Error::NoSupportedKeys)
        }
        Ok(Device{
            input: d.into_event_stream()?,
            output: vdb.build()?,
            })
    }
}

impl event::KeyboardEventSource for Device {
    fn recv(&mut self) ->Result<event::KeyboardEvent> {
        let ev = block_on(self.input.next_event())?;
        Ok(ie_into_ke(ev))
    }

}

fn ie_into_ke(ev: evdev::InputEvent) -> event::KeyboardEvent {
    event::KeyboardEvent {
        time: ev.timestamp(),
        code: ec_into_kc(evdev::Key::new(ev.code())),
        state: i32_into_ks(ev.value()),
    }
}

fn ec_into_kc(ec: evdev::Key) -> event::KeyCode {
    match ec {
        evdev::Key::KEY_RESERVED => event::KeyCode::KC_RESERVED,
        evdev::Key::KEY_ESC => event::KeyCode::KC_ESC,
        evdev::Key::KEY_1 => event::KeyCode::KC_1,
        evdev::Key::KEY_2 => event::KeyCode::KC_2,
        evdev::Key::KEY_3 => event::KeyCode::KC_3,
        evdev::Key::KEY_4 => event::KeyCode::KC_4,
        evdev::Key::KEY_5 => event::KeyCode::KC_5,
        evdev::Key::KEY_6 => event::KeyCode::KC_6,
        evdev::Key::KEY_7 => event::KeyCode::KC_7,
        evdev::Key::KEY_8 => event::KeyCode::KC_8,
        evdev::Key::KEY_9 => event::KeyCode::KC_9,
        evdev::Key::KEY_0 => event::KeyCode::KC_0,
        evdev::Key::KEY_MINUS => event::KeyCode::KC_MINUS,
        evdev::Key::KEY_EQUAL => event::KeyCode::KC_EQUAL,
        evdev::Key::KEY_BACKSPACE => event::KeyCode::KC_BACKSPACE,
        evdev::Key::KEY_TAB => event::KeyCode::KC_TAB,
        evdev::Key::KEY_Q => event::KeyCode::KC_Q,
        evdev::Key::KEY_W => event::KeyCode::KC_W,
        evdev::Key::KEY_E => event::KeyCode::KC_E,
        evdev::Key::KEY_R => event::KeyCode::KC_R,
        evdev::Key::KEY_T => event::KeyCode::KC_T,
        evdev::Key::KEY_Y => event::KeyCode::KC_Y,
        evdev::Key::KEY_U => event::KeyCode::KC_U,
        evdev::Key::KEY_I => event::KeyCode::KC_I,
        evdev::Key::KEY_O => event::KeyCode::KC_O,
        evdev::Key::KEY_P => event::KeyCode::KC_P,
        evdev::Key::KEY_LEFTBRACE => event::KeyCode::KC_LEFTBRACE,
        evdev::Key::KEY_RIGHTBRACE => event::KeyCode::KC_RIGHTBRACE,
        evdev::Key::KEY_ENTER => event::KeyCode::KC_ENTER,
        evdev::Key::KEY_LEFTCTRL => event::KeyCode::KC_LEFTCTRL,
        evdev::Key::KEY_A => event::KeyCode::KC_A,
        evdev::Key::KEY_S => event::KeyCode::KC_S,
        evdev::Key::KEY_D => event::KeyCode::KC_D,
        evdev::Key::KEY_F => event::KeyCode::KC_F,
        evdev::Key::KEY_G => event::KeyCode::KC_G,
        evdev::Key::KEY_H => event::KeyCode::KC_H,
        evdev::Key::KEY_J => event::KeyCode::KC_J,
        evdev::Key::KEY_K => event::KeyCode::KC_K,
        evdev::Key::KEY_L => event::KeyCode::KC_L,
        evdev::Key::KEY_SEMICOLON => event::KeyCode::KC_SEMICOLON,
        evdev::Key::KEY_APOSTROPHE => event::KeyCode::KC_APOSTROPHE,
        evdev::Key::KEY_GRAVE => event::KeyCode::KC_GRAVE,
        evdev::Key::KEY_LEFTSHIFT => event::KeyCode::KC_LEFTSHIFT,
        evdev::Key::KEY_BACKSLASH => event::KeyCode::KC_BACKSLASH,
        evdev::Key::KEY_Z => event::KeyCode::KC_Z,
        evdev::Key::KEY_X => event::KeyCode::KC_X,
        evdev::Key::KEY_C => event::KeyCode::KC_C,
        evdev::Key::KEY_V => event::KeyCode::KC_V,
        evdev::Key::KEY_B => event::KeyCode::KC_B,
        evdev::Key::KEY_N => event::KeyCode::KC_N,
        evdev::Key::KEY_M => event::KeyCode::KC_M,
        evdev::Key::KEY_COMMA => event::KeyCode::KC_COMMA,
        evdev::Key::KEY_DOT => event::KeyCode::KC_DOT,
        evdev::Key::KEY_SLASH => event::KeyCode::KC_SLASH,
        evdev::Key::KEY_RIGHTSHIFT => event::KeyCode::KC_RIGHTSHIFT,
        evdev::Key::KEY_KPASTERISK => event::KeyCode::KC_KPASTERISK,
        evdev::Key::KEY_LEFTALT => event::KeyCode::KC_LEFTALT,
        evdev::Key::KEY_SPACE => event::KeyCode::KC_SPACE,
        evdev::Key::KEY_CAPSLOCK => event::KeyCode::KC_CAPSLOCK,
        evdev::Key::KEY_F1 => event::KeyCode::KC_F1,
        evdev::Key::KEY_F2 => event::KeyCode::KC_F2,
        evdev::Key::KEY_F3 => event::KeyCode::KC_F3,
        evdev::Key::KEY_F4 => event::KeyCode::KC_F4,
        evdev::Key::KEY_F5 => event::KeyCode::KC_F5,
        evdev::Key::KEY_F6 => event::KeyCode::KC_F6,
        evdev::Key::KEY_F7 => event::KeyCode::KC_F7,
        evdev::Key::KEY_F8 => event::KeyCode::KC_F8,
        evdev::Key::KEY_F9 => event::KeyCode::KC_F9,
        evdev::Key::KEY_F10 => event::KeyCode::KC_F10,
        evdev::Key::KEY_NUMLOCK => event::KeyCode::KC_NUMLOCK,
        evdev::Key::KEY_SCROLLLOCK => event::KeyCode::KC_SCROLLLOCK,
        evdev::Key::KEY_KP7 => event::KeyCode::KC_KP7,
        evdev::Key::KEY_KP8 => event::KeyCode::KC_KP8,
        evdev::Key::KEY_KP9 => event::KeyCode::KC_KP9,
        evdev::Key::KEY_KPMINUS => event::KeyCode::KC_KPMINUS,
        evdev::Key::KEY_KP4 => event::KeyCode::KC_KP4,
        evdev::Key::KEY_KP5 => event::KeyCode::KC_KP5,
        evdev::Key::KEY_KP6 => event::KeyCode::KC_KP6,
        evdev::Key::KEY_KPPLUS => event::KeyCode::KC_KPPLUS,
        evdev::Key::KEY_KP1 => event::KeyCode::KC_KP1,
        evdev::Key::KEY_KP2 => event::KeyCode::KC_KP2,
        evdev::Key::KEY_KP3 => event::KeyCode::KC_KP3,
        evdev::Key::KEY_KP0 => event::KeyCode::KC_KP0,
        evdev::Key::KEY_KPDOT => event::KeyCode::KC_KPDOT,
        evdev::Key::KEY_ZENKAKUHANKAKU => event::KeyCode::KC_ZENKAKUHANKAKU,
        evdev::Key::KEY_102ND => event::KeyCode::KC_102ND,
        evdev::Key::KEY_F11 => event::KeyCode::KC_F11,
        evdev::Key::KEY_F12 => event::KeyCode::KC_F12,
        evdev::Key::KEY_RO => event::KeyCode::KC_RO,
        evdev::Key::KEY_KATAKANA => event::KeyCode::KC_KATAKANA,
        evdev::Key::KEY_HIRAGANA => event::KeyCode::KC_HIRAGANA,
        evdev::Key::KEY_HENKAN => event::KeyCode::KC_HENKAN,
        evdev::Key::KEY_KATAKANAHIRAGANA => event::KeyCode::KC_KATAKANAHIRAGANA,
        evdev::Key::KEY_MUHENKAN => event::KeyCode::KC_MUHENKAN,
        evdev::Key::KEY_KPJPCOMMA => event::KeyCode::KC_KPJPCOMMA,
        evdev::Key::KEY_KPENTER => event::KeyCode::KC_KPENTER,
        evdev::Key::KEY_RIGHTCTRL => event::KeyCode::KC_RIGHTCTRL,
        evdev::Key::KEY_KPSLASH => event::KeyCode::KC_KPSLASH,
        evdev::Key::KEY_SYSRQ => event::KeyCode::KC_SYSRQ,
        evdev::Key::KEY_RIGHTALT => event::KeyCode::KC_RIGHTALT,
        evdev::Key::KEY_LINEFEED => event::KeyCode::KC_LINEFEED,
        evdev::Key::KEY_HOME => event::KeyCode::KC_HOME,
        evdev::Key::KEY_UP => event::KeyCode::KC_UP,
        evdev::Key::KEY_PAGEUP => event::KeyCode::KC_PAGEUP,
        evdev::Key::KEY_LEFT => event::KeyCode::KC_LEFT,
        evdev::Key::KEY_RIGHT => event::KeyCode::KC_RIGHT,
        evdev::Key::KEY_END => event::KeyCode::KC_END,
        evdev::Key::KEY_DOWN => event::KeyCode::KC_DOWN,
        evdev::Key::KEY_PAGEDOWN => event::KeyCode::KC_PAGEDOWN,
        evdev::Key::KEY_INSERT => event::KeyCode::KC_INSERT,
        evdev::Key::KEY_DELETE => event::KeyCode::KC_DELETE,
        evdev::Key::KEY_MACRO => event::KeyCode::KC_MACRO,
        evdev::Key::KEY_MUTE => event::KeyCode::KC_MUTE,
        evdev::Key::KEY_VOLUMEDOWN => event::KeyCode::KC_VOLUMEDOWN,
        evdev::Key::KEY_VOLUMEUP => event::KeyCode::KC_VOLUMEUP,
        evdev::Key::KEY_POWER => event::KeyCode::KC_POWER,
        evdev::Key::KEY_KPEQUAL => event::KeyCode::KC_KPEQUAL,
        evdev::Key::KEY_KPPLUSMINUS => event::KeyCode::KC_KPPLUSMINUS,
        evdev::Key::KEY_PAUSE => event::KeyCode::KC_PAUSE,
        evdev::Key::KEY_SCALE => event::KeyCode::KC_SCALE,
        evdev::Key::KEY_KPCOMMA => event::KeyCode::KC_KPCOMMA,
        evdev::Key::KEY_HANGEUL => event::KeyCode::KC_HANGEUL,
        evdev::Key::KEY_HANJA => event::KeyCode::KC_HANJA,
        evdev::Key::KEY_YEN => event::KeyCode::KC_YEN,
        evdev::Key::KEY_LEFTMETA => event::KeyCode::KC_LEFTMETA,
        evdev::Key::KEY_RIGHTMETA => event::KeyCode::KC_RIGHTMETA,
        evdev::Key::KEY_COMPOSE => event::KeyCode::KC_COMPOSE,
        evdev::Key::KEY_STOP => event::KeyCode::KC_STOP,
        evdev::Key::KEY_AGAIN => event::KeyCode::KC_AGAIN,
        evdev::Key::KEY_PROPS => event::KeyCode::KC_PROPS,
        evdev::Key::KEY_UNDO => event::KeyCode::KC_UNDO,
        evdev::Key::KEY_FRONT => event::KeyCode::KC_FRONT,
        evdev::Key::KEY_COPY => event::KeyCode::KC_COPY,
        evdev::Key::KEY_OPEN => event::KeyCode::KC_OPEN,
        evdev::Key::KEY_PASTE => event::KeyCode::KC_PASTE,
        evdev::Key::KEY_FIND => event::KeyCode::KC_FIND,
        evdev::Key::KEY_CUT => event::KeyCode::KC_CUT,
        evdev::Key::KEY_HELP => event::KeyCode::KC_HELP,
        evdev::Key::KEY_MENU => event::KeyCode::KC_MENU,
        evdev::Key::KEY_CALC => event::KeyCode::KC_CALC,
        evdev::Key::KEY_SETUP => event::KeyCode::KC_SETUP,
        evdev::Key::KEY_SLEEP => event::KeyCode::KC_SLEEP,
        evdev::Key::KEY_WAKEUP => event::KeyCode::KC_WAKEUP,
        evdev::Key::KEY_FILE => event::KeyCode::KC_FILE,
        evdev::Key::KEY_SENDFILE => event::KeyCode::KC_SENDFILE,
        evdev::Key::KEY_DELETEFILE => event::KeyCode::KC_DELETEFILE,
        evdev::Key::KEY_XFER => event::KeyCode::KC_XFER,
        evdev::Key::KEY_PROG1 => event::KeyCode::KC_PROG1,
        evdev::Key::KEY_PROG2 => event::KeyCode::KC_PROG2,
        evdev::Key::KEY_WWW => event::KeyCode::KC_WWW,
        evdev::Key::KEY_MSDOS => event::KeyCode::KC_MSDOS,
        evdev::Key::KEY_COFFEE => event::KeyCode::KC_COFFEE,
        evdev::Key::KEY_ROTATE_DISPLAY => event::KeyCode::KC_ROTATE_DISPLAY,
        evdev::Key::KEY_CYCLEWINDOWS => event::KeyCode::KC_CYCLEWINDOWS,
        evdev::Key::KEY_MAIL => event::KeyCode::KC_MAIL,
        evdev::Key::KEY_BOOKMARKS => event::KeyCode::KC_BOOKMARKS,
        evdev::Key::KEY_COMPUTER => event::KeyCode::KC_COMPUTER,
        evdev::Key::KEY_BACK => event::KeyCode::KC_BACK,
        evdev::Key::KEY_FORWARD => event::KeyCode::KC_FORWARD,
        evdev::Key::KEY_CLOSECD => event::KeyCode::KC_CLOSECD,
        evdev::Key::KEY_EJECTCD => event::KeyCode::KC_EJECTCD,
        evdev::Key::KEY_EJECTCLOSECD => event::KeyCode::KC_EJECTCLOSECD,
        evdev::Key::KEY_NEXTSONG => event::KeyCode::KC_NEXTSONG,
        evdev::Key::KEY_PLAYPAUSE => event::KeyCode::KC_PLAYPAUSE,
        evdev::Key::KEY_PREVIOUSSONG => event::KeyCode::KC_PREVIOUSSONG,
        evdev::Key::KEY_STOPCD => event::KeyCode::KC_STOPCD,
        evdev::Key::KEY_RECORD => event::KeyCode::KC_RECORD,
        evdev::Key::KEY_REWIND => event::KeyCode::KC_REWIND,
        evdev::Key::KEY_PHONE => event::KeyCode::KC_PHONE,
        evdev::Key::KEY_ISO => event::KeyCode::KC_ISO,
        evdev::Key::KEY_CONFIG => event::KeyCode::KC_CONFIG,
        evdev::Key::KEY_HOMEPAGE => event::KeyCode::KC_HOMEPAGE,
        evdev::Key::KEY_REFRESH => event::KeyCode::KC_REFRESH,
        evdev::Key::KEY_EXIT => event::KeyCode::KC_EXIT,
        evdev::Key::KEY_MOVE => event::KeyCode::KC_MOVE,
        evdev::Key::KEY_EDIT => event::KeyCode::KC_EDIT,
        evdev::Key::KEY_SCROLLUP => event::KeyCode::KC_SCROLLUP,
        evdev::Key::KEY_SCROLLDOWN => event::KeyCode::KC_SCROLLDOWN,
        evdev::Key::KEY_KPLEFTPAREN => event::KeyCode::KC_KPLEFTPAREN,
        evdev::Key::KEY_KPRIGHTPAREN => event::KeyCode::KC_KPRIGHTPAREN,
        evdev::Key::KEY_NEW => event::KeyCode::KC_NEW,
        evdev::Key::KEY_REDO => event::KeyCode::KC_REDO,
        evdev::Key::KEY_F13 => event::KeyCode::KC_F13,
        evdev::Key::KEY_F14 => event::KeyCode::KC_F14,
        evdev::Key::KEY_F15 => event::KeyCode::KC_F15,
        evdev::Key::KEY_F16 => event::KeyCode::KC_F16,
        evdev::Key::KEY_F17 => event::KeyCode::KC_F17,
        evdev::Key::KEY_F18 => event::KeyCode::KC_F18,
        evdev::Key::KEY_F19 => event::KeyCode::KC_F19,
        evdev::Key::KEY_F20 => event::KeyCode::KC_F20,
        evdev::Key::KEY_F21 => event::KeyCode::KC_F21,
        evdev::Key::KEY_F22 => event::KeyCode::KC_F22,
        evdev::Key::KEY_F23 => event::KeyCode::KC_F23,
        evdev::Key::KEY_F24 => event::KeyCode::KC_F24,
        evdev::Key::KEY_PLAYCD => event::KeyCode::KC_PLAYCD,
        evdev::Key::KEY_PAUSECD => event::KeyCode::KC_PAUSECD,
        evdev::Key::KEY_PROG3 => event::KeyCode::KC_PROG3,
        evdev::Key::KEY_PROG4 => event::KeyCode::KC_PROG4,
        evdev::Key::KEY_DASHBOARD => event::KeyCode::KC_DASHBOARD,
        evdev::Key::KEY_SUSPEND => event::KeyCode::KC_SUSPEND,
        evdev::Key::KEY_CLOSE => event::KeyCode::KC_CLOSE,
        evdev::Key::KEY_PLAY => event::KeyCode::KC_PLAY,
        evdev::Key::KEY_FASTFORWARD => event::KeyCode::KC_FASTFORWARD,
        evdev::Key::KEY_BASSBOOST => event::KeyCode::KC_BASSBOOST,
        evdev::Key::KEY_PRINT => event::KeyCode::KC_PRINT,
        evdev::Key::KEY_HP => event::KeyCode::KC_HP,
        evdev::Key::KEY_CAMERA => event::KeyCode::KC_CAMERA,
        evdev::Key::KEY_SOUND => event::KeyCode::KC_SOUND,
        evdev::Key::KEY_QUESTION => event::KeyCode::KC_QUESTION,
        evdev::Key::KEY_EMAIL => event::KeyCode::KC_EMAIL,
        evdev::Key::KEY_CHAT => event::KeyCode::KC_CHAT,
        evdev::Key::KEY_SEARCH => event::KeyCode::KC_SEARCH,
        evdev::Key::KEY_CONNECT => event::KeyCode::KC_CONNECT,
        evdev::Key::KEY_FINANCE => event::KeyCode::KC_FINANCE,
        evdev::Key::KEY_SPORT => event::KeyCode::KC_SPORT,
        evdev::Key::KEY_SHOP => event::KeyCode::KC_SHOP,
        evdev::Key::KEY_ALTERASE => event::KeyCode::KC_ALTERASE,
        evdev::Key::KEY_CANCEL => event::KeyCode::KC_CANCEL,
        evdev::Key::KEY_BRIGHTNESSDOWN => event::KeyCode::KC_BRIGHTNESSDOWN,
        evdev::Key::KEY_BRIGHTNESSUP => event::KeyCode::KC_BRIGHTNESSUP,
        evdev::Key::KEY_MEDIA => event::KeyCode::KC_MEDIA,
        evdev::Key::KEY_SWITCHVIDEOMODE => event::KeyCode::KC_SWITCHVIDEOMODE,
        evdev::Key::KEY_KBDILLUMTOGGLE => event::KeyCode::KC_KBDILLUMTOGGLE,
        evdev::Key::KEY_KBDILLUMDOWN => event::KeyCode::KC_KBDILLUMDOWN,
        evdev::Key::KEY_KBDILLUMUP => event::KeyCode::KC_KBDILLUMUP,
        evdev::Key::KEY_SEND => event::KeyCode::KC_SEND,
        evdev::Key::KEY_REPLY => event::KeyCode::KC_REPLY,
        evdev::Key::KEY_FORWARDMAIL => event::KeyCode::KC_FORWARDMAIL,
        evdev::Key::KEY_SAVE => event::KeyCode::KC_SAVE,
        evdev::Key::KEY_DOCUMENTS => event::KeyCode::KC_DOCUMENTS,
        evdev::Key::KEY_BATTERY => event::KeyCode::KC_BATTERY,
        evdev::Key::KEY_BLUETOOTH => event::KeyCode::KC_BLUETOOTH,
        evdev::Key::KEY_WLAN => event::KeyCode::KC_WLAN,
        evdev::Key::KEY_UWB => event::KeyCode::KC_UWB,
        evdev::Key::KEY_UNKNOWN => event::KeyCode::KC_UNKNOWN,
        evdev::Key::KEY_VIDEO_NEXT => event::KeyCode::KC_VIDEO_NEXT,
        evdev::Key::KEY_VIDEO_PREV => event::KeyCode::KC_VIDEO_PREV,
        evdev::Key::KEY_BRIGHTNESS_CYCLE => event::KeyCode::KC_BRIGHTNESS_CYCLE,
        evdev::Key::KEY_BRIGHTNESS_AUTO => event::KeyCode::KC_BRIGHTNESS_AUTO,
        evdev::Key::KEY_DISPLAY_OFF => event::KeyCode::KC_DISPLAY_OFF,
        evdev::Key::KEY_WWAN => event::KeyCode::KC_WWAN,
        evdev::Key::KEY_RFKILL => event::KeyCode::KC_RFKILL,
        evdev::Key::KEY_MICMUTE => event::KeyCode::KC_MICMUTE,
        evdev::Key::KEY_OK => event::KeyCode::KC_OK,
        evdev::Key::KEY_SELECT => event::KeyCode::KC_SELECT,
        evdev::Key::KEY_GOTO => event::KeyCode::KC_GOTO,
        evdev::Key::KEY_CLEAR => event::KeyCode::KC_CLEAR,
        evdev::Key::KEY_POWER2 => event::KeyCode::KC_POWER2,
        evdev::Key::KEY_OPTION => event::KeyCode::KC_OPTION,
        evdev::Key::KEY_INFO => event::KeyCode::KC_INFO,
        evdev::Key::KEY_TIME => event::KeyCode::KC_TIME,
        evdev::Key::KEY_VENDOR => event::KeyCode::KC_VENDOR,
        evdev::Key::KEY_ARCHIVE => event::KeyCode::KC_ARCHIVE,
        evdev::Key::KEY_PROGRAM => event::KeyCode::KC_PROGRAM,
        evdev::Key::KEY_CHANNEL => event::KeyCode::KC_CHANNEL,
        evdev::Key::KEY_FAVORITES => event::KeyCode::KC_FAVORITES,
        evdev::Key::KEY_EPG => event::KeyCode::KC_EPG,
        evdev::Key::KEY_PVR => event::KeyCode::KC_PVR,
        evdev::Key::KEY_MHP => event::KeyCode::KC_MHP,
        evdev::Key::KEY_LANGUAGE => event::KeyCode::KC_LANGUAGE,
        evdev::Key::KEY_TITLE => event::KeyCode::KC_TITLE,
        evdev::Key::KEY_SUBTITLE => event::KeyCode::KC_SUBTITLE,
        evdev::Key::KEY_ANGLE => event::KeyCode::KC_ANGLE,
        evdev::Key::KEY_FULL_SCREEN => event::KeyCode::KC_FULL_SCREEN,
        evdev::Key::KEY_KEYBOARD => event::KeyCode::KC_KEYBOARD,
        evdev::Key::KEY_PC => event::KeyCode::KC_PC,
        evdev::Key::KEY_TV => event::KeyCode::KC_TV,
        evdev::Key::KEY_TV2 => event::KeyCode::KC_TV2,
        evdev::Key::KEY_VCR => event::KeyCode::KC_VCR,
        evdev::Key::KEY_VCR2 => event::KeyCode::KC_VCR2,
        evdev::Key::KEY_SAT => event::KeyCode::KC_SAT,
        evdev::Key::KEY_SAT2 => event::KeyCode::KC_SAT2,
        evdev::Key::KEY_CD => event::KeyCode::KC_CD,
        evdev::Key::KEY_TAPE => event::KeyCode::KC_TAPE,
        evdev::Key::KEY_RADIO => event::KeyCode::KC_RADIO,
        evdev::Key::KEY_TUNER => event::KeyCode::KC_TUNER,
        evdev::Key::KEY_PLAYER => event::KeyCode::KC_PLAYER,
        evdev::Key::KEY_TEXT => event::KeyCode::KC_TEXT,
        evdev::Key::KEY_DVD => event::KeyCode::KC_DVD,
        evdev::Key::KEY_AUX => event::KeyCode::KC_AUX,
        evdev::Key::KEY_MP3 => event::KeyCode::KC_MP3,
        evdev::Key::KEY_AUDIO => event::KeyCode::KC_AUDIO,
        evdev::Key::KEY_VIDEO => event::KeyCode::KC_VIDEO,
        evdev::Key::KEY_DIRECTORY => event::KeyCode::KC_DIRECTORY,
        evdev::Key::KEY_LIST => event::KeyCode::KC_LIST,
        evdev::Key::KEY_MEMO => event::KeyCode::KC_MEMO,
        evdev::Key::KEY_CALENDAR => event::KeyCode::KC_CALENDAR,
        evdev::Key::KEY_RED => event::KeyCode::KC_RED,
        evdev::Key::KEY_GREEN => event::KeyCode::KC_GREEN,
        evdev::Key::KEY_YELLOW => event::KeyCode::KC_YELLOW,
        evdev::Key::KEY_BLUE => event::KeyCode::KC_BLUE,
        evdev::Key::KEY_CHANNELUP => event::KeyCode::KC_CHANNELUP,
        evdev::Key::KEY_CHANNELDOWN => event::KeyCode::KC_CHANNELDOWN,
        evdev::Key::KEY_FIRST => event::KeyCode::KC_FIRST,
        evdev::Key::KEY_LAST => event::KeyCode::KC_LAST,
        evdev::Key::KEY_AB => event::KeyCode::KC_AB,
        evdev::Key::KEY_NEXT => event::KeyCode::KC_NEXT,
        evdev::Key::KEY_RESTART => event::KeyCode::KC_RESTART,
        evdev::Key::KEY_SLOW => event::KeyCode::KC_SLOW,
        evdev::Key::KEY_SHUFFLE => event::KeyCode::KC_SHUFFLE,
        evdev::Key::KEY_BREAK => event::KeyCode::KC_BREAK,
        evdev::Key::KEY_PREVIOUS => event::KeyCode::KC_PREVIOUS,
        evdev::Key::KEY_DIGITS => event::KeyCode::KC_DIGITS,
        evdev::Key::KEY_TEEN => event::KeyCode::KC_TEEN,
        evdev::Key::KEY_TWEN => event::KeyCode::KC_TWEN,
        evdev::Key::KEY_VIDEOPHONE => event::KeyCode::KC_VIDEOPHONE,
        evdev::Key::KEY_GAMES => event::KeyCode::KC_GAMES,
        evdev::Key::KEY_ZOOMIN => event::KeyCode::KC_ZOOMIN,
        evdev::Key::KEY_ZOOMOUT => event::KeyCode::KC_ZOOMOUT,
        evdev::Key::KEY_ZOOMRESET => event::KeyCode::KC_ZOOMRESET,
        evdev::Key::KEY_WORDPROCESSOR => event::KeyCode::KC_WORDPROCESSOR,
        evdev::Key::KEY_EDITOR => event::KeyCode::KC_EDITOR,
        evdev::Key::KEY_SPREADSHEET => event::KeyCode::KC_SPREADSHEET,
        evdev::Key::KEY_GRAPHICSEDITOR => event::KeyCode::KC_GRAPHICSEDITOR,
        evdev::Key::KEY_PRESENTATION => event::KeyCode::KC_PRESENTATION,
        evdev::Key::KEY_DATABASE => event::KeyCode::KC_DATABASE,
        evdev::Key::KEY_NEWS => event::KeyCode::KC_NEWS,
        evdev::Key::KEY_VOICEMAIL => event::KeyCode::KC_VOICEMAIL,
        evdev::Key::KEY_ADDRESSBOOK => event::KeyCode::KC_ADDRESSBOOK,
        evdev::Key::KEY_MESSENGER => event::KeyCode::KC_MESSENGER,
        evdev::Key::KEY_DISPLAYTOGGLE => event::KeyCode::KC_DISPLAYTOGGLE,
        evdev::Key::KEY_SPELLCHECK => event::KeyCode::KC_SPELLCHECK,
        evdev::Key::KEY_LOGOFF => event::KeyCode::KC_LOGOFF,
        evdev::Key::KEY_DOLLAR => event::KeyCode::KC_DOLLAR,
        evdev::Key::KEY_EURO => event::KeyCode::KC_EURO,
        evdev::Key::KEY_FRAMEBACK => event::KeyCode::KC_FRAMEBACK,
        evdev::Key::KEY_FRAMEFORWARD => event::KeyCode::KC_FRAMEFORWARD,
        evdev::Key::KEY_CONTEXT_MENU => event::KeyCode::KC_CONTEXT_MENU,
        evdev::Key::KEY_MEDIA_REPEAT => event::KeyCode::KC_MEDIA_REPEAT,
        evdev::Key::KEY_10CHANNELSUP => event::KeyCode::KC_10CHANNELSUP,
        evdev::Key::KEY_10CHANNELSDOWN => event::KeyCode::KC_10CHANNELSDOWN,
        evdev::Key::KEY_IMAGES => event::KeyCode::KC_IMAGES,
        evdev::Key::KEY_DEL_EOL => event::KeyCode::KC_DEL_EOL,
        evdev::Key::KEY_DEL_EOS => event::KeyCode::KC_DEL_EOS,
        evdev::Key::KEY_INS_LINE => event::KeyCode::KC_INS_LINE,
        evdev::Key::KEY_DEL_LINE => event::KeyCode::KC_DEL_LINE,
        evdev::Key::KEY_FN => event::KeyCode::KC_FN,
        evdev::Key::KEY_FN_ESC => event::KeyCode::KC_FN_ESC,
        evdev::Key::KEY_FN_F1 => event::KeyCode::KC_FN_F1,
        evdev::Key::KEY_FN_F2 => event::KeyCode::KC_FN_F2,
        evdev::Key::KEY_FN_F3 => event::KeyCode::KC_FN_F3,
        evdev::Key::KEY_FN_F4 => event::KeyCode::KC_FN_F4,
        evdev::Key::KEY_FN_F5 => event::KeyCode::KC_FN_F5,
        evdev::Key::KEY_FN_F6 => event::KeyCode::KC_FN_F6,
        evdev::Key::KEY_FN_F7 => event::KeyCode::KC_FN_F7,
        evdev::Key::KEY_FN_F8 => event::KeyCode::KC_FN_F8,
        evdev::Key::KEY_FN_F9 => event::KeyCode::KC_FN_F9,
        evdev::Key::KEY_FN_F10 => event::KeyCode::KC_FN_F10,
        evdev::Key::KEY_FN_F11 => event::KeyCode::KC_FN_F11,
        evdev::Key::KEY_FN_F12 => event::KeyCode::KC_FN_F12,
        evdev::Key::KEY_FN_1 => event::KeyCode::KC_FN_1,
        evdev::Key::KEY_FN_2 => event::KeyCode::KC_FN_2,
        evdev::Key::KEY_FN_D => event::KeyCode::KC_FN_D,
        evdev::Key::KEY_FN_E => event::KeyCode::KC_FN_E,
        evdev::Key::KEY_FN_F => event::KeyCode::KC_FN_F,
        evdev::Key::KEY_FN_S => event::KeyCode::KC_FN_S,
        evdev::Key::KEY_FN_B => event::KeyCode::KC_FN_B,
        evdev::Key::KEY_BRL_DOT1 => event::KeyCode::KC_BRL_DOT1,
        evdev::Key::KEY_BRL_DOT2 => event::KeyCode::KC_BRL_DOT2,
        evdev::Key::KEY_BRL_DOT3 => event::KeyCode::KC_BRL_DOT3,
        evdev::Key::KEY_BRL_DOT4 => event::KeyCode::KC_BRL_DOT4,
        evdev::Key::KEY_BRL_DOT5 => event::KeyCode::KC_BRL_DOT5,
        evdev::Key::KEY_BRL_DOT6 => event::KeyCode::KC_BRL_DOT6,
        evdev::Key::KEY_BRL_DOT7 => event::KeyCode::KC_BRL_DOT7,
        evdev::Key::KEY_BRL_DOT8 => event::KeyCode::KC_BRL_DOT8,
        evdev::Key::KEY_BRL_DOT9 => event::KeyCode::KC_BRL_DOT9,
        evdev::Key::KEY_BRL_DOT10 => event::KeyCode::KC_BRL_DOT10,
        evdev::Key::KEY_NUMERIC_0 => event::KeyCode::KC_NUMERIC_0,
        evdev::Key::KEY_NUMERIC_1 => event::KeyCode::KC_NUMERIC_1,
        evdev::Key::KEY_NUMERIC_2 => event::KeyCode::KC_NUMERIC_2,
        evdev::Key::KEY_NUMERIC_3 => event::KeyCode::KC_NUMERIC_3,
        evdev::Key::KEY_NUMERIC_4 => event::KeyCode::KC_NUMERIC_4,
        evdev::Key::KEY_NUMERIC_5 => event::KeyCode::KC_NUMERIC_5,
        evdev::Key::KEY_NUMERIC_6 => event::KeyCode::KC_NUMERIC_6,
        evdev::Key::KEY_NUMERIC_7 => event::KeyCode::KC_NUMERIC_7,
        evdev::Key::KEY_NUMERIC_8 => event::KeyCode::KC_NUMERIC_8,
        evdev::Key::KEY_NUMERIC_9 => event::KeyCode::KC_NUMERIC_9,
        evdev::Key::KEY_NUMERIC_STAR => event::KeyCode::KC_NUMERIC_STAR,
        evdev::Key::KEY_NUMERIC_POUND => event::KeyCode::KC_NUMERIC_POUND,
        evdev::Key::KEY_NUMERIC_A => event::KeyCode::KC_NUMERIC_A,
        evdev::Key::KEY_NUMERIC_B => event::KeyCode::KC_NUMERIC_B,
        evdev::Key::KEY_NUMERIC_C => event::KeyCode::KC_NUMERIC_C,
        evdev::Key::KEY_NUMERIC_D => event::KeyCode::KC_NUMERIC_D,
        evdev::Key::KEY_CAMERA_FOCUS => event::KeyCode::KC_CAMERA_FOCUS,
        evdev::Key::KEY_WPS_BUTTON => event::KeyCode::KC_WPS_BUTTON,
        evdev::Key::KEY_TOUCHPAD_TOGGLE => event::KeyCode::KC_TOUCHPAD_TOGGLE,
        evdev::Key::KEY_TOUCHPAD_ON => event::KeyCode::KC_TOUCHPAD_ON,
        evdev::Key::KEY_TOUCHPAD_OFF => event::KeyCode::KC_TOUCHPAD_OFF,
        evdev::Key::KEY_CAMERA_ZOOMIN => event::KeyCode::KC_CAMERA_ZOOMIN,
        evdev::Key::KEY_CAMERA_ZOOMOUT => event::KeyCode::KC_CAMERA_ZOOMOUT,
        evdev::Key::KEY_CAMERA_UP => event::KeyCode::KC_CAMERA_UP,
        evdev::Key::KEY_CAMERA_DOWN => event::KeyCode::KC_CAMERA_DOWN,
        evdev::Key::KEY_CAMERA_LEFT => event::KeyCode::KC_CAMERA_LEFT,
        evdev::Key::KEY_CAMERA_RIGHT => event::KeyCode::KC_CAMERA_RIGHT,
        evdev::Key::KEY_ATTENDANT_ON => event::KeyCode::KC_ATTENDANT_ON,
        evdev::Key::KEY_ATTENDANT_OFF => event::KeyCode::KC_ATTENDANT_OFF,
        evdev::Key::KEY_ATTENDANT_TOGGLE => event::KeyCode::KC_ATTENDANT_TOGGLE,
        evdev::Key::KEY_LIGHTS_TOGGLE => event::KeyCode::KC_LIGHTS_TOGGLE,
        evdev::Key::KEY_ALS_TOGGLE => event::KeyCode::KC_ALS_TOGGLE,
        evdev::Key::KEY_BUTTONCONFIG => event::KeyCode::KC_BUTTONCONFIG,
        evdev::Key::KEY_TASKMANAGER => event::KeyCode::KC_TASKMANAGER,
        evdev::Key::KEY_JOURNAL => event::KeyCode::KC_JOURNAL,
        evdev::Key::KEY_CONTROLPANEL => event::KeyCode::KC_CONTROLPANEL,
        evdev::Key::KEY_SCREENSAVER => event::KeyCode::KC_SCREENSAVER,
        evdev::Key::KEY_VOICECOMMAND => event::KeyCode::KC_VOICECOMMAND,
        evdev::Key::KEY_ASSISTANT => event::KeyCode::KC_ASSISTANT,
        evdev::Key::KEY_BRIGHTNESS_MIN => event::KeyCode::KC_BRIGHTNESS_MIN,
        evdev::Key::KEY_BRIGHTNESS_MAX => event::KeyCode::KC_BRIGHTNESS_MAX,
        evdev::Key::KEY_KBDINPUTASSIST_PREV => event::KeyCode::KC_KBDINPUTASSIST_PREV,
        evdev::Key::KEY_KBDINPUTASSIST_NEXT => event::KeyCode::KC_KBDINPUTASSIST_NEXT,
        evdev::Key::KEY_KBDINPUTASSIST_PREVGROUP => event::KeyCode::KC_KBDINPUTASSIST_PREVGROUP,
        evdev::Key::KEY_KBDINPUTASSIST_NEXTGROUP => event::KeyCode::KC_KBDINPUTASSIST_NEXTGROUP,
        evdev::Key::KEY_KBDINPUTASSIST_ACCEPT => event::KeyCode::KC_KBDINPUTASSIST_ACCEPT,
        evdev::Key::KEY_KBDINPUTASSIST_CANCEL => event::KeyCode::KC_KBDINPUTASSIST_CANCEL,
        evdev::Key::KEY_RIGHT_UP => event::KeyCode::KC_RIGHT_UP,
        evdev::Key::KEY_RIGHT_DOWN => event::KeyCode::KC_RIGHT_DOWN,
        evdev::Key::KEY_LEFT_UP => event::KeyCode::KC_LEFT_UP,
        evdev::Key::KEY_LEFT_DOWN => event::KeyCode::KC_LEFT_DOWN,
        evdev::Key::KEY_ROOT_MENU => event::KeyCode::KC_ROOT_MENU,
        evdev::Key::KEY_MEDIA_TOP_MENU => event::KeyCode::KC_MEDIA_TOP_MENU,
        evdev::Key::KEY_NUMERIC_11 => event::KeyCode::KC_NUMERIC_11,
        evdev::Key::KEY_NUMERIC_12 => event::KeyCode::KC_NUMERIC_12,
        evdev::Key::KEY_AUDIO_DESC => event::KeyCode::KC_AUDIO_DESC,
        evdev::Key::KEY_3D_MODE => event::KeyCode::KC_3D_MODE,
        evdev::Key::KEY_NEXT_FAVORITE => event::KeyCode::KC_NEXT_FAVORITE,
        evdev::Key::KEY_STOP_RECORD => event::KeyCode::KC_STOP_RECORD,
        evdev::Key::KEY_PAUSE_RECORD => event::KeyCode::KC_PAUSE_RECORD,
        evdev::Key::KEY_VOD => event::KeyCode::KC_VOD,
        evdev::Key::KEY_UNMUTE => event::KeyCode::KC_UNMUTE,
        evdev::Key::KEY_FASTREVERSE => event::KeyCode::KC_FASTREVERSE,
        evdev::Key::KEY_SLOWREVERSE => event::KeyCode::KC_SLOWREVERSE,
        evdev::Key::KEY_DATA => event::KeyCode::KC_DATA,
        evdev::Key::KEY_ONSCREEN_KEYBOARD => event::KeyCode::KC_ONSCREEN_KEYBOARD,
        _ => event::KeyCode::NotImplemented,
    }
}

fn i32_into_ks(i: i32) -> event::KeyState {
    match i {
        1 => event::KeyState::Up,
        0 => event::KeyState::Down,
        2 => event::KeyState::Held,
        _ => event::KeyState::NotImplemented,
    }
}
