[package]
name = "qsk-types"
version = "0.1.0"
edition = "2021"

[dependencies]
num = "~0.3"
num-derive = "~0.3"
num-traits = "~0.2"

serde = {version = "~1.0", features = ["derive"]}
serde_json = "~1.0"
