name: cargo build & test
on:
  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * 5'
  push:
    branches: [ 'main' ]
    paths-ignore:
      - "**/docs/**"
      - "**.md"
  pull_request:
    paths-ignore:
      - "**/docs/**"
      - "**.md"
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - qsk-types
          - qsk-macros
          - ./
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: test
        env:
          DIRECTORY: ${{ matrix.directory }}
        run: |
          cd $DIRECTORY
          cargo test
      - name: build
        env:
          DIRECTORY: ${{ matrix.directory }}
        run: |
          cd $DIRECTORY
          cargo build --release --all-features

  qsk-template-reify-and-build:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: mytemplate
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v2
      - uses: cargo-generate/cargo-generate-action@v0.11.0
        with:
          name: ${{ env.PROJECT_NAME }}
          template: qsk-template
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      # we need to move the generated project to a temp folder, away from the template project
      # otherwise `cargo` runs would fail
      # see https://github.com/rust-lang/cargo/issues/9922
      - run: |
          mv $PROJECT_NAME ${{ runner.temp }}/
          cd ${{ runner.temp }}/$PROJECT_NAME
          cargo build
