name: cargo build & test
on:
  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * 5'
  push:
    branches: [ 'main' ]
    paths-ignore:
      - "**/docs/**"
      - "**.md"
  pull_request:
    paths-ignore:
      - "**/docs/**"
      - "**.md"
    types:
      - opened
      - reopened
      - synchronized
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: mytemplate
    strategy:
      matrix:
        directory:
          - qsk-types
          - qsk-macros
          - ./
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: test
        env:
          DIRECTORY: ${{ matrix.directory }}
        run: |
        cd $DIRECTORY
        cargo test
      - name: build
        env:
          DIRECTORY: ${{ matrix.directory }}
        run: |
        cd $DIRECTORY
        cargo build --release --all-features
